//! Bootstrap pipeline — Vision → PRD → Plan template generation.

use serde::{Deserialize, Serialize};
use std::path::Path;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum BootstrapPhase {
    Vision,
    Prd,
    Brand,
    Plan,
    Execute,
}

impl BootstrapPhase {
    pub fn all() -> &'static [BootstrapPhase] {
        &[
            BootstrapPhase::Vision,
            BootstrapPhase::Prd,
            BootstrapPhase::Brand,
            BootstrapPhase::Plan,
            BootstrapPhase::Execute,
        ]
    }

    pub fn label(&self) -> &'static str {
        match self {
            BootstrapPhase::Vision => "Vision",
            BootstrapPhase::Prd => "PRD",
            BootstrapPhase::Brand => "Brand",
            BootstrapPhase::Plan => "Plan",
            BootstrapPhase::Execute => "Execute",
        }
    }

    pub fn icon(&self) -> &'static str {
        match self {
            BootstrapPhase::Vision => "🔭",
            BootstrapPhase::Prd => "📋",
            BootstrapPhase::Brand => "🎨",
            BootstrapPhase::Plan => "📐",
            BootstrapPhase::Execute => "🔨",
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BootstrapState {
    pub project_name: String,
    pub current_phase: BootstrapPhase,
    pub completed: Vec<BootstrapPhase>,
    pub started_at: String,
}

impl BootstrapState {
    pub fn new(project_name: &str) -> Self {
        Self {
            project_name: project_name.to_string(),
            current_phase: BootstrapPhase::Vision,
            completed: Vec::new(),
            started_at: chrono::Utc::now().to_rfc3339(),
        }
    }

    pub fn mark_done(&mut self, phase: BootstrapPhase) {
        if !self.completed.contains(&phase) {
            self.completed.push(phase);
        }
        // advance to next phase
        let all = BootstrapPhase::all();
        if let Some(pos) = all.iter().position(|p| *p == phase) {
            if pos + 1 < all.len() {
                self.current_phase = all[pos + 1];
            }
        }
    }

    pub fn is_done(&self, phase: BootstrapPhase) -> bool {
        self.completed.contains(&phase)
    }

    pub fn progress_pct(&self) -> f32 {
        let total = BootstrapPhase::all().len() as f32;
        self.completed.len() as f32 / total * 100.0
    }

    pub fn state_path(project_dir: &Path) -> std::path::PathBuf {
        project_dir.join(".omega").join("bootstrap.json")
    }

    pub fn load(project_dir: &Path) -> Option<Self> {
        let path = Self::state_path(project_dir);
        std::fs::read_to_string(path)
            .ok()
            .and_then(|s| serde_json::from_str(&s).ok())
    }

    pub fn save(&self, project_dir: &Path) -> anyhow::Result<()> {
        let path = Self::state_path(project_dir);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let json = serde_json::to_string_pretty(self)?;
        std::fs::write(path, json)?;
        Ok(())
    }
}

pub fn generate_vision_template(project_name: &str, project_dir: &Path) -> anyhow::Result<()> {
    let content = format!(
        r#"# Vision — {name}

## Internal Compass

> _One sentence that acts as a decision filter for every feature, design choice, and priority._

[Fill in: "We exist to ___"]

## Soul Statement

[What is {name} at its deepest level? Not features — feeling. Not users — humans.]

## Design Principles

1. **[Principle 1]** — [Why this matters for {name}]
2. **[Principle 2]** — [How this constrains decisions]
3. **[Principle 3]** — [What this means in practice]

## Personas

### Primary Persona

- **Name:** [Realistic name]
- **Role:** [Job title / life role]
- **Pain:** [The core frustration this product solves]
- **Goal:** [What "success" looks like for them]
- **Context:** [When/where they use this product]

### Secondary Persona

- **Name:**
- **Role:**
- **Pain:**
- **Goal:**

## Emotional Positioning

| Dimension | This product feels like... | NOT like... |
|-----------|---------------------------|-------------|
| Tone | | |
| Speed | | |
| Complexity | | |
| Trust | | |

## What {name} Is NOT

- NOT a [competitor/category to avoid]
- NOT a [misperception to prevent]
- NOT a [scope creep to block]

## Success Metrics (qualitative)

- Users say: "___"
- Users feel: ___
- Users recommend because: ___

---

_Generated by OmegaOS Bootstrap Pipeline_
_Fill in each section through the `/vision` Socratic discovery process._
"#,
        name = project_name,
    );

    let path = project_dir.join("docs").join("VISION.md");
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&path, content)?;
    Ok(())
}

pub fn generate_prd_template(project_name: &str, project_dir: &Path) -> anyhow::Result<()> {
    let content = format!(
        r#"# PRD — {name}

## 1. Overview

**Product:** {name}
**Vision:** [Reference VISION.md Internal Compass]
**Target:** [Primary persona from VISION.md]

## 2. Problem Statement

[What problem does {name} solve? Be specific about the pain point.]

## 3. Goals & Non-Goals

### Goals
1.
2.
3.

### Non-Goals
1.
2.

## 4. Features

| ID | Feature | Priority | Complexity | Status |
|----|---------|----------|------------|--------|
| F-001 | | P0 | M | planned |
| F-002 | | P0 | L | planned |
| F-003 | | P1 | M | planned |

### Feature Detail Template

#### F-001: [Feature Name]

**User Story:** As a [persona], I want to [action] so that [benefit].

**Acceptance Criteria:**
- [ ]
- [ ]
- [ ]

**Technical Notes:**
-

## 5. Technical Architecture

### Stack
-

### Data Model
-

### API Surface
-

## 6. Design Constraints

- [From VISION.md design principles]
-

## 7. Success Metrics (quantitative)

| Metric | Target | Measurement |
|--------|--------|-------------|
| | | |

## 8. Timeline

| Phase | Duration | Deliverable |
|-------|----------|-------------|
| Foundation | | |
| Core | | |
| Polish | | |
| Launch | | |

---

_Generated by OmegaOS Bootstrap Pipeline_
_Refine through the `/prd` research + specification process._
"#,
        name = project_name,
    );

    let path = project_dir.join("docs").join("PRD.md");
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&path, content)?;
    Ok(())
}

pub fn generate_feature_spec(
    feature_id: &str,
    feature_name: &str,
    project_dir: &Path,
) -> anyhow::Result<()> {
    let content = format!(
        r#"# {id}: {name}

## User Story

As a [persona], I want to [action] so that [benefit].

## Acceptance Criteria

- [ ]
- [ ]
- [ ]

## Technical Design

### Components
-

### Data Flow
-

### API Endpoints
-

## Edge Cases

1.
2.

## Dependencies

- Depends on: [other feature IDs]
- Blocks: [other feature IDs]

## Test Plan

- [ ] Unit tests for [component]
- [ ] Integration test for [flow]
- [ ] E2E test for [user journey]
"#,
        id = feature_id,
        name = feature_name,
    );

    let dir = project_dir.join("docs").join("FEATURES");
    std::fs::create_dir_all(&dir)?;
    let filename = format!("{}-{}.md", feature_id, slug(feature_name));
    std::fs::write(dir.join(filename), content)?;
    Ok(())
}

fn slug(s: &str) -> String {
    s.to_lowercase()
        .chars()
        .map(|c| if c.is_alphanumeric() { c } else { '-' })
        .collect::<String>()
        .trim_matches('-')
        .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bootstrap_state_progression() {
        let mut state = BootstrapState::new("TestApp");
        assert_eq!(state.current_phase, BootstrapPhase::Vision);
        assert!(!state.is_done(BootstrapPhase::Vision));

        state.mark_done(BootstrapPhase::Vision);
        assert!(state.is_done(BootstrapPhase::Vision));
        assert_eq!(state.current_phase, BootstrapPhase::Prd);

        state.mark_done(BootstrapPhase::Prd);
        assert_eq!(state.current_phase, BootstrapPhase::Brand);
        assert!((state.progress_pct() - 40.0).abs() < 0.1);
    }

    #[test]
    fn template_generation() {
        let tmp = std::env::temp_dir().join("omega-bootstrap-test");
        let _ = std::fs::remove_dir_all(&tmp);
        std::fs::create_dir_all(&tmp).unwrap();

        generate_vision_template("TestApp", &tmp).unwrap();
        assert!(tmp.join("docs/VISION.md").exists());

        generate_prd_template("TestApp", &tmp).unwrap();
        assert!(tmp.join("docs/PRD.md").exists());

        generate_feature_spec("F-001", "User Auth", &tmp).unwrap();
        assert!(tmp.join("docs/FEATURES/F-001-user-auth.md").exists());

        let _ = std::fs::remove_dir_all(&tmp);
    }
}
