#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════
# OmegaOS Transcription installer — local open-source audio transcription.
#
# Installs faster-whisper (MIT, github.com/SYSTRAN/faster-whisper), a
# CTranslate2-based reimplementation of OpenAI Whisper. Runs 100% locally:
# no API key, no network call during transcription, no per-minute billing.
#
# Supports: MP3, WAV, M4A, OGG, FLAC, MP4, and any format ffmpeg can decode.
# Languages: all 99 languages Whisper supports, including FR and EN.
# Models: tiny (<100MB) → base (~140MB) → medium (~1.4GB) → large-v3 (~3GB).
#         Default model "base" is downloaded on FIRST USE, not at install time.
#
# After install, use:
#   omega-transcribe <audio_file>
#   omega-transcribe <file> --model medium --language fr --output srt
#
# IS run by install.sh: no paid account required, modest install (~30MB for
# the Python package; the model is lazy-downloaded on first use).
#
# Idempotent, and NEVER fatal: a failure here must not abort an OmegaOS install.
# ═══════════════════════════════════════════════════════════════════════════
set -uo pipefail

OMEGA_DIR="${OMEGA_DIR:-$HOME/.omega}"
TOOL_DIR="$OMEGA_DIR/tools/transcription"
VENV="$TOOL_DIR/.venv"
BIN_DIR="$OMEGA_DIR/bin"
INSTALL_DIR="${INSTALL_DIR:-$HOME/.local/bin}"
SCRIPT_SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/omega-transcribe.py"

info() { printf '\033[36m[transcription]\033[0m %s\n' "$*"; }
warn() { printf '\033[33m[transcription]\033[0m %s\n' "$*"; }

# ── Preflight ─────────────────────────────────────────────────────────────────
PY="$(command -v python3 || true)"
[[ -n "$PY" ]] || { warn "python3 not found — skipping"; exit 0; }
"$PY" -c 'import sys; sys.exit(0 if sys.version_info >= (3,10) else 1)' 2>/dev/null \
    || { warn "python3 >= 3.10 required — skipping"; exit 0; }
"$PY" -c 'import venv' 2>/dev/null \
    || { warn "python3-venv missing (apt install python3-venv) — skipping"; exit 0; }

# ffmpeg is required by faster-whisper for audio decoding
if ! command -v ffmpeg >/dev/null 2>&1; then
    warn "ffmpeg not found — trying to install (apt-get / brew)"
    if command -v apt-get >/dev/null 2>&1; then
        sudo apt-get install -y -q ffmpeg 2>/dev/null \
            || warn "apt-get ffmpeg failed — transcription may fail on some formats"
    elif command -v brew >/dev/null 2>&1; then
        brew install ffmpeg 2>/dev/null \
            || warn "brew ffmpeg failed — transcription may fail on some formats"
    else
        warn "cannot auto-install ffmpeg; install it manually for full format support"
    fi
fi

# ── Venv ──────────────────────────────────────────────────────────────────────
mkdir -p "$TOOL_DIR" "$BIN_DIR" "$INSTALL_DIR"
if [[ ! -x "$VENV/bin/python" ]]; then
    info "creating venv at $VENV"
    "$PY" -m venv "$VENV" 2>/dev/null || { warn "venv creation failed — skipping"; exit 0; }
fi
"$VENV/bin/pip" install --quiet --upgrade pip 2>/dev/null || true

# ── Install faster-whisper ────────────────────────────────────────────────────
# faster-whisper uses CTranslate2 for efficient CPU/GPU inference.
# The 'base' Whisper model (~140MB) is downloaded on first use, not here,
# so install.sh stays fast and offline-friendly.
if "$VENV/bin/pip" install --quiet "faster-whisper>=1.0.0" 2>/dev/null; then
    VER="$("$VENV/bin/python" -c 'import faster_whisper; print(faster_whisper.__version__)' 2>/dev/null || echo '?')"
    info "faster-whisper $VER installed"
else
    warn "pip install faster-whisper failed — transcription not available (OmegaOS install continues)"
    exit 0
fi

# ── Install the omega-transcribe CLI ─────────────────────────────────────────
# Wrapper shell script: delegates to the venv Python so no activation needed.
WRAPPER="$BIN_DIR/omega-transcribe"
SCRIPT_DEST="$TOOL_DIR/omega-transcribe.py"

# Copy the Python script into the tool dir
if [[ -f "$SCRIPT_SRC" ]]; then
    cp "$SCRIPT_SRC" "$SCRIPT_DEST"
else
    warn "omega-transcribe.py source not found at $SCRIPT_SRC — skipping CLI install"
    exit 0
fi

cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# omega-transcribe — local audio transcription via faster-whisper
# Generated by install-transcription.sh
exec "$VENV/bin/python" "$SCRIPT_DEST" "\$@"
EOF
chmod +x "$WRAPPER"
ln -sf "$WRAPPER" "$INSTALL_DIR/omega-transcribe" 2>/dev/null || true

info "installed: omega-transcribe → $WRAPPER"
info "usage: omega-transcribe <audio_file> [--model base|medium|large-v3] [--language fr|en] [--output txt|json|srt]"
info "note: the Whisper 'base' model (~140MB) will be downloaded on first use"

exit 0
