#!/usr/bin/env python3
"""Generate OS/README.md, the human index of the AGENTIK {OS} suite.

Derived from OS/_registry.json plus what is actually on disk, so the index can
never claim an OS exists when its directory does not, and never drifts from the
TUI roster the way the hand-maintained table did.

Usage:
    python3 gen_readme.py            write OS/README.md
    python3 gen_readme.py --stdout   print instead of writing
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OS_DIR = os.path.dirname(HERE)
REG = json.load(open(os.path.join(OS_DIR, "_registry.json"), encoding="utf-8"))
MARK = "<!-- agentik:scaffold -->"

CONTRACT = list(REG["contract"]["files"]) + [
    "COMMANDS/README.md", "MEMORY/policy.md", "EVALS/README.md",
    "WORKFLOWS/README.md", "PROMPTS/README.md", "REFERENCES/README.md",
    "TOOLS/README.md", "EXAMPLES/README.md",
] + [f"INTERFACES/{i}" for i in REG["contract"]["INTERFACES"]] \
  + [f"ADAPTERS/{a}" for a in REG["contract"]["ADAPTERS"]]


def unit_state(slug):
    root = os.path.join(OS_DIR, slug)
    if not os.path.isdir(root):
        return "absent", 0, 0
    present = authored = 0
    for rel in CONTRACT:
        p = os.path.join(root, rel)
        if os.path.isfile(p):
            present += 1
            try:
                with open(p, encoding="utf-8", errors="replace") as fh:
                    if MARK not in fh.read(4096):
                        authored += 1
            except Exception:
                pass
    return "present", present, authored


def main():
    L = []
    A = L.append
    total = REG["total"]

    A("# OS — the AGENTIK {OS} suite")
    A("")
    A(f"This directory holds the AgentikOS product line: **{total} operative systems**")
    A(f"in **{len(REG['groups'])} groups**. Each subdirectory is ONE operative system.")
    A("")
    A("The suite is surfaced in the TUI under the **OS** tab (`omega menu`) and")
    A("installed to `~/.omega/os/` by `install.sh`.")
    A("")
    A("> An Agentik OS is not a prompt and not a document. It is a system with its")
    A("> own operating specification, workflows, commands, memory rules,")
    A("> evaluations and per-environment adapters, installed and run by the")
    A("> Agentik Runtime.")
    A("")
    A("## Do not edit this file")
    A("")
    A("`README.md`, the TUI roster (`crates/omega-core/src/os_products.rs`) and")
    A("`_registry.json` are all GENERATED from one source:")
    A("")
    A("```")
    A("OS/_tools/suite.py          the registry: add or reorder an OS HERE")
    A("        |")
    A("        +-- suite.py registry        ->  OS/_registry.json")
    A("        +-- gen_os_products.py       ->  crates/omega-core/src/os_products.rs")
    A("        +-- gen_readme.py            ->  OS/README.md")
    A("        +-- scaffold.py build        ->  OS/<slug>/ file contract")
    A("```")
    A("")
    A("After changing `suite.py`, re-run all four, then `cargo test -p omega-core`.")
    A("")
    A("## The file contract")
    A("")
    A("Every OS carries the same structure, so a user who learns one has learned")
    A("all of them and the Runtime can operate on any of them:")
    A("")
    A("```")
    A("<slug>/")
    A("├── README.md      human entry point")
    A("├── OS.md          complete operating specification")
    A("├── SYSTEM.md      AI and system instructions")
    A("├── SKILL.md       capabilities and procedures")
    A("├── SETUP.md       initial configuration")
    A("├── manifest.json  machine-readable metadata")
    A("├── CHANGELOG.md   what changed between versions")
    A("├── WORKFLOWS/     repeatable processes")
    A("├── COMMANDS/      every command, explained")
    A("├── PROMPTS/       reusable prompt units")
    A("├── REFERENCES/    knowledge this OS needs")
    A("├── MEMORY/        what may be remembered, updated, forgotten")
    A("├── TOOLS/         external capabilities it may use")
    A("├── EVALS/         tests that prove it behaves correctly")
    A("├── EXAMPLES/      worked examples")
    A("├── INTERFACES/    chat, artifact, dashboard, generative UI")
    A("└── ADAPTERS/      chatgpt, claude, gemini, codex")
    A("```")
    A("")
    A("## Reading the status column")
    A("")
    A("| Status | Meaning |")
    A("|---|---|")
    A("| **authored** | Content written for this OS, beyond the scaffold |")
    A("| **scaffold** | Structure complete, content not yet authored |")
    A("| **absent** | Directory missing (a registry entry with no folder yet) |")
    A("")
    A("Status is measured from disk at generation time, never asserted by hand.")
    A("")
    A("## The suite")
    A("")

    tot_p = tot_a = 0
    for g in REG["groups"]:
        members = [o for o in REG["os"] if o["group"] == g["key"]]
        A(f"### {g['label']} — {g['purpose']}")
        A("")
        A("| # | OS | Slug | What it is for | Status |")
        A("|---|----|------|----------------|--------|")
        for o in members:
            state, present, authored = unit_state(o["slug"])
            tot_p += present
            tot_a += authored
            n = len(CONTRACT)
            if state == "absent":
                status = "**absent**"
            elif authored >= n:
                status = "**authored**"
            elif authored > 0:
                status = f"scaffold (+{authored} authored)"
            else:
                status = "scaffold"
            A(f"| {o['num']:02d} | {o['name']} {{OS}} | `{o['slug']}` "
              f"| {o['tagline']} | {status} |")
        A("")

    n = len(CONTRACT) * REG["total"]
    A("## Coverage")
    A("")
    A(f"- Units in the registry: **{REG['total']}**")
    A(f"- Contract files required: **{n}** ({len(CONTRACT)} per OS)")
    A(f"- Contract files present: **{tot_p}** ({100 * tot_p // n if n else 0}%)")
    A(f"- Of those, authored beyond scaffold: **{tot_a}** ({100 * tot_a // n if n else 0}%)")
    A("")
    A("Regenerate this section with `python3 _tools/gen_readme.py`.")
    A("")
    A("## Aliases retired")
    A("")
    A("These directories are duplicates of a canonical unit. They are kept until")
    A("their content is merged, and must not be re-created:")
    A("")
    A("| Duplicate | Canonical |")
    A("|---|---|")
    for dup, canon in sorted(REG["aliases"].items()):
        A(f"| `{dup}` | `{canon}` |")
    A("")

    out = "\n".join(L)
    if "--stdout" in sys.argv:
        print(out)
    else:
        path = os.path.join(OS_DIR, "README.md")
        open(path, "w", encoding="utf-8").write(out)
        print(f"wrote {path} ({len(out)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
